### ISSUE TITLE
No Delete in Type of Transactions

### ISSUE THREAD

**Issue by Jeremy-M-Int** [INTERPOL-Innovation-Centre/ANSI-NIST-XML-ITL-Implementation#1]
There does not seem to be a type of transaction to handle Delete requests.
Need to confirm the reasoning behind removing it compared to the previous version (v5.03) and if one would still be needed.

**Comment by diefenbecker** [comment]
To check whether messages like DFPs (without biometric data) need to be implemented within a NIST file or if a simple message structure isn´t the easier way.
Also to check list of TOTs included in current XSD compared with the ones discribed in the document. XSD does contain also the old TOTs from binary version 5.03.

**Comment by epcondon** [comment]
1)	The TOT definitions in v6.0 and earlier tagged binary version, for search type transaction indicated both the probe and target biometric (e.g. CPS =Criminal Print-to-Print Search), and  is missing from the proposed TOT description and therefore it is ambiguous what some are intended to cover.  The descriptions need to be expanded.
It is not clear if CCS is a Print Set (or Person) being submitted for a search  against unidentified latent mark (or other unknow stains) or it is a case/latent mark being submitted for searching against prints (or persons). (The comment that this is existing is confusing, is it intended to be a replacement for MPS TOT?)
2)	There are some biometric searching modalities missing from the TOT listing (e.g. PMS (Print to Mark),  (MMS) Mark to Mark. On the v6.00 this were not included (but are in v5.03) because Interpol were not intending to support. It would be good to include to help clarify what the other TOTs are and remove ambiguity. Also on the Interpol AFIS working group it was suggested that these are search modalities that are now available and supported. Many countries use the Interpol standard as the basis for their national implementations and including these missing TOTs will ensure commonality of usage going forward (e.g Prum).
3)	On the v6.0 working group there was discussion on the NPS (Non-criminal Print-to-Print Search). It was in v 5.03 and retained in v 6.0 because it is believed that there are business scenarios/ use case where the person who biometrics are being submitted for searching has not had them taken in connection with criminality but for other purposes (e.g. border control or vetting) and there may be different considerations about what can be searched against on receipt and whether the biometrics can be exchanged with 3rd parties. Given some of the use case described in working groups, it is a surprise that his is not being included.
4)	Within the ATP transaction, the description indicates that there is the potential to optionally search.  It is unclear how this optionality is invoked. Perhaps having separate TOTs for “Store only” and “Search and Store” would be an easier mechanism? (otherwise the standard needs to be updated to cover).
5)	DBS - Database Search. I think there needs to be clarity on the purpose of this in the context of request to Interpol. Is this intended to search the AFIS, DNA and facial sub systems or is this intended to mirror the nominals details searching already offered? Is it a way of checking if something has bene added or not to a biometric store. The standard needs to also define what elements for database search purposes are allowed (references, names, DOB etc) and whether these are AND or ORed,  if multiple parameters are provided. The handling of wild card characters, case and full or partial matching also needs to be clarified.
6) DFC the comment "revived and renamed to distinguish between Search Only and Search and Store)" above  is not logical. Previous TOT  from 5.03 would have been USR and has no search component.

**Comment by Jeremy-M-Int** [comment]
New list of ToTs defined and agreed with the INSIWG:

RESQUESTS:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">


ToT | Description | Comment
-- | -- | --
CPS | Central/Common/Complete   Person Search -> Global Searches on a Person     - search modalities determined by receiving system         FP -> TP/TP (PP/PP), TP/UL,   PP/UP         FA -> FA/FA, FA/UF |  
PPS | Person-To-Person Search (e.g. Border/Identity Checks)         FP -> TP/TP (PP/PP)         FA -> FA/FA | Type 2 ?     Also compatible with PRUM as a Print-to-Print Search if only FP (Type   14/15) are provided
PUS | Person-To-Unknown   Search (e.g. Known Individual)         FP -> TP/UL, PP/UP         FA -> FA/UF | Type   2 ?
CCS | Central/Common/Complete Case Search -> Global Searches on a Case (multiple latents/evidences)      - search   modalities determined by receiving system         FP -> LT/TP, LT/UL, LP/PP,   LP/UP         FA -> LF/FA, LF/UF |  
UPS | Unknown-To-Person   Search (e.g. Dead body identification (DVI), Crime   solving only)         FP -> LT/TP, LP/PP         FA -> LF/FA | Type   2 ?
UUS | Unknown-To-Unknown Search (e.g. Crime Pattern and Forensic Intelligence/Analysis,   Deduplication of cases)         FP -> LT/UL, LP/UP         FA -> LF/UF | Type 2 ?
ATP | Add   To Person -> Global Search and Store on a Person     Note: Person to be   created if not existing. An update/edit may require a combination of DFP and   ATP.     - search modalities determined by receiving system         FP -> TP/TP (PP/PP), TP/UL,   PP/UP         FA -> FA/FA, FA/UF |  
ATC | Add To Case -> Global Search and Store on a Case (multiple   latents/evidences)     Note: Case to be   created if not existing. An update/edit may require a combination of DFC and   ATC.      - search modalities determined by   receiving system         FP -> LT/TP, LT/UL, LP/PP,   LP/UP         FA -> LF/FA, LF/UF |  
DFP | Delete   From Person     -> At Person level     -> At Registration level | Type   2 field to identify the registration
DFC | Delete From Case     -> At Case level     -> At Event level     -> At Data level (Evidence & Latent) | Type 2 field (multi-subfields) to   identify the data
BDQ | Biometric Data reQuest     -> Case/Person level     -> Registration/Event level     -> Evidence/Latent level (for cases only) |  



</body>

</html>



RESPONSES:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">


ToT | Description | Comment
-- | -- | --
ACK | ACKnowledgement | with confirmation of data   references
SRE | Search REsult |  
ERR | ERRor |  
BDR | Biometric Data   Response     -> Case/Person level     -> Registration/Event level     -> Evidence/Latent level (for cases only) |  



</body>

</html>

And for compatibility with PRÜM:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JEM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#0563C1" vlink="#954F72">


ToT | Description | Comment
-- | -- | --
PMS | Print-To-Mark   Search         FP -> TP/UL, PP/UP | Compatibility   w/ PRUM
MPS | Mark-To-Print Search | Compatibility w/ PRUM
MMS | Mark-To-Mark Search | Compatibility   w/ PRUM



</body>

</html>
